/****************
qemu with -kernel file.bin ==> start to execute from 0x10000 ==>
file.bin must be loaded to 0x10000 ==> . = 0x10000
************/
ENTRY(reset_handler)
SECTIONS
{
  . = 0x00000;
  .text : {
      ts.o
      *(.text .rodata)
  }
  .data : { *(.data) }
  .bss : { *(.bss) }
  . = ALIGN(8);
  . = . + 0x1000;   /* 4kB of stack memory */
  svc_stack = .;
  . = . + 0x1000;   /* 4kB of irq stack memory */
  irq_stack = .;
}

